---
- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: install server utils
    package:
      name:
        - screen
  - name: install stoneblock2 (1/2)
    command: https://api.modpacks.ch/public/modpack/4/153/server/linux
